// Top-level build file where you can add configuration options common to all sub-projects/modules.

task clean(type: Delete) {
    delete rootProject.buildDir
}



subprojects {
    ext {
        JAVA_VERSION = 25
    }

    plugins.withType(JavaPlugin) {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(25)
            }
            sourceCompatibility = JavaVersion.toVersion(25)
            targetCompatibility = JavaVersion.toVersion(25)
        }
    }
}


task buildAllDistributions {
    dependsOn ':desktop:buildAllDistributions'

    doLast {
        println(" #### Check the individual modules build/distributions folders for distributable zips etc #### ")
    }
}

